#+title: Keybindings Reference

You actually don't need this file. Emacs has an absolutely wonderful help
system that neither Vim nor Helix has anything close to — it is self-documented.

You can always place cursor on any variable or command you're interested in,
press =: helpful-at-point= (or =M-x helpful-at-point=) from [[https://github.com/Wilfred/helpful][helpful]] package to see
the full documentation about it. Bind it to key for more convenient access. Vim
uses =K= key for such things (which is available while there is only one cursor in
the buffer), another good choice is =M= since it's unused in Hel.
#+begin_src emacs-lisp
(hel-keymap-set emacs-lisp-mode-map :state 'normal
  "M" 'helpful-at-point)
#+end_src

Hel keybindings are defined in the =hel-keybindings.el= file. Using the advice
above, you can read the documentation for any command bound to a key you’re
interested in.

* Motion state

Motion state is the default state for special buffers: grep results, error
lists, file managers — anything not intended for text editing. A simple
heuristic is used: if any letter key is not self-inserting, Hel enables Motion
state; otherwise, it uses Normal state.

In Motion state Hel provide service keys to control Emacs itself.

- =:= :: Emacs analoug of command pallete. (Native key is =M-x=)

- =C-:= ::
  Open command palette with only the commands that make sense in the current
  buffer. (Native key is =M-X=)

- =M-u= ::
  Emacs universal argument. Native key is =C-u=, but Hel use it for scrolling,
  and =M-u= by default is bound to ~upcase-word~, for which Hel has itself version
  on =M-`= or =gU=.

- =SPC= :: Leader key (if ~hel-leader~ extension is installed)

- =i= ::
  Switch to Normal state. This allows you to select and copy arbitrary text in
  special modes. To switch back, use =zx= or =C-x C-s= (~hel-motion-state~).

** Windows

- =C-w s= / =C-w v= :: Split window *horizontally* / *vertically*.

- =C-w c= :: Close current window, if it was the last window on the tab —
  close the tab.

- =C-w d= :: Kill current buffer.

- =C-w q= :: =C-w d= + =C-w c=

- =C-w o= :: Close all other windows.

- =C-w w= :: Cycle to the next window.

- =C-w= + =h=, =j=, =k=, =l= :: Go to the window toward the direction.

- =C-w= + =H=, =J=, =K=, =L= :: Move window in direction.

- =C-w RET= :: Display the buffer of the next command in the same window.

- =C-w n= :: Display the buffer of the next command in a new window.

- =C-w r= :: Revert buffer.

All window commands also duplicated with =C-= prefix for convenience: =C-w C-s=,
=C-w C-v=, etc.

A secondary prefix for window commands is available on =C-c w=. It is useful when
the =C-w= prefix is unavailable, such as in terminal emulators, ~picture-mode~,
and similar modes.

** Scrolling

Scrolling commands are taken from Vim.

- =C-d= / =C-u= ::
  Scroll *down* / *up* half of the page. If a numeric prefix is provided, scroll
  this amount of lines and remember it for further use. To reset it use 0
  prefix. (like in Vim)

- =C-f= / =C-b= :: Scroll *down* / *up* full page.

- =C-e= / =C-y= :: Scroll *down* / *up* COUNT lines.

- =zt= / =zb= :: Scroll current line to the *top* / *bottom* border of the screen.

- =zz= :: Scrolls current line to the eye level.

  If you want Vim default behavior set following variable *before* requiring Hel:
  #+begin_src emacs-lisp
  (setopt hel-want-zz-scroll-to-center t)
  #+end_src

** Buffers

- =C-w r= :: Revert current buffer.

- =C-w d= :: Kill current buffer.
- =C-w q= :: Kill current buffer and close window.

- =C-w z= ::
  Burry current buffer: put it the end of the list of all buffers.
  Mnemonics: =z= is the last letter.

- =[b= / =]b= :: *previous* / *next* buffer

- =C-w x= :: ~scratch-buffer~

* Normal state

All keys available in Motion state are also work in Normal state.

** Motions

- =h=, =j=, =k=, =l= :: Arrows.

- =w=, =b=, =e= :: word motions
- =W=, =B=, =E= :: WORD motions

- =f= / =F= :: Find *next* / *previous* char.
  While hints are active use =n= / =N= to repeat motion.

- =t= / =T= :: Till *next* / *previous* char.
  While hints are active use =n= / =N= to repeat motion.

- =gs= / =gl= :: Move to the *beginning* / *end* of a line.

- =gh= :: Move to the beginning of a line skipping indentation.

- =gg= / =G= :: Go to the *first* / *last* line of the buffer.

- ={= / =}= or =[p= / =]p= :: Move over paragraphs.

- =(= / =)= ::
  When there is only one cursor in the buffer, moves over sentences in major
  modes derived from ~text-mode~, or over functions in major modes derived from
  ~prog-mode~.

- =[f= / =]f= :: Move over functions.

- =[s= / =]s= :: Move over sentences.

*** Easymotion

- =gw= / =gb= ::
  Place hints at all words *forward* / *backward* and select the chosen one.

- =gW= / =gB= ::
  Place hints at all WORDS *forward* / *backward* and select the chosen one.

- =gj= / =gk= :: Go to line *down* / *up*.

** Changes

- =i= / =a= :: insert / append: Switch to Insert state *before* / *after* selection.

- =I= / =A= :: Insert / Append: Switch to Insert state at the *start* / *end* of the line.

- =o= / =O= ::
  Open: add new line *bellow* / *above* the current line and switch to Insert state.

- =d= :: Cut selection: delete it from buffer and put into ~kill-ring~.

- =D= :: Delete selection.

- =c= ::
  Change. Delete selection and switch to Insert state. When executed in empty
  line — insert indentation and switch to Insert state.

- =u= / =U= :: *undo* / *redo*.

- =y= :: Copy selection into ~kill-ring~.

- =p= / =P= :: Paste last entry from ~kill-ring~ *after* / *before* selection.

- =C-p= / =C-n= ::
  Replace just-pasted text with *next* / *previous* element from ~kill-ring~.
  This is wrappers around Emacs built-in ~yank-pop~ command.

- =R= ::
  Replace selection with last entry from ~kill-ring~. You can use =C-p= / =C-n=
  immediately after this command to choose next/previous element from ~kill-ring~.

- =~= :: Invert case of characters.

- =`= / =M-`= or =gu= / =gU= :: Convert selection to *lower* / *upper* case.

- =] SPC= / =[ SPC= :: Add empty line *bellow* / *above* the current line.

** Multiple cursors

- =M-right mouse= :: Create secondary cursor on click.

- =C= / =M-c= :: Copy selection (cursor) *down* / *up*.

- =s= ::
  Interactively enter regexp and create cursors for all matches withing active
  selections.

- =S= ::
  Interactively enter regexp and create cursors for complements to all matches
  to regexp withing active selections.

- =M-s= :: Split selections on newlines.

- =gv= :: Restore last multiple cursors positions.

*** Keys active while there are multiple cursors

- =K= / =M-K= :: Keep/remove selections matching to regexp.

- =,= :: Remove all secondary cursors.

- =M-,= :: Remove main cursor.

- =&= :: Align selections.

- =M-minus= :: Merge all selections into single one.

- =(= / =)= :: Rotate main selection *backward* / *forward*.

- =M-(= / =M-)= :: Rotate selections content *backward* / *forward*.

** Selections

- =v= :: Toggle extend selection.

- =x= / =X= ::
  Select current visual (if ~visual-line-mode~ is active) or logical line on first
  invocation. On subsequent calls *extend* / *contract* linewise selection down
  when cursor is at the end of the selection, or up when cursor is at the
  beginning of the selection.

- =%= :: Select whole buffer.

- =;= :: Collapse selection onto a single cursor.

- =M-;= or =g;= :: Exchange point and mark.

- =_= :: Trim whitespaces and newlines from the both ends of selections.

- =J= :: Join lines inside selection.

*** Mark
Here the word "mark" is used as synonym to "select", to form the mnemonic rule
for =m= prefix. Also, this is in line with Emacs tradition which has commands like
~mark-word~ which use the word "mark" in this particular sense.

- =mw=, =mW= or =miw=, =miW= :: Mark inner word/WORD.

- =maw=, =maW= :: Mark around word/WORD.

- =m.= or =mis= :: Mark inner sentence.

- =mas= :: Mark around sentence.

- =mp= or =mip= :: Mark inner paragraph.

- =map= :: Mark around paragraph.

- =mf= or =mif= :: Mark inner function.

- =maf= :: Mark around funciton.

- =m"=, =m'=, =m`= or =mi"=, =mi'=, =mi`= ::
  Mark inside ="= / ='= / =`= quotes.

- =ma"=, =ma'=, =ma`= ::
  Mark around ="= / ='= / =`= quotes.

- =m(=, =m)= or =mi(=, =mi)= :: Mark inside =(= =)=.
- =ma(=, =ma)= :: Mark around =(= =)=.

- =m[=, =m]= or =mi[=, =mi]= :: Mark inside =[= =]=.
- =ma[=, =ma]= :: Mark around =[= =]=.

- =m{=, =m}= or =mi{=, =mi}= :: Mark inside ={= =}=.
- =ma{=, =ma}= :: Mark around ={= =}=.

- =m<=, =m>= or =mi<=, =mi>= :: Mark inside =<= =>=.
- =ma<=, =ma>= :: Mark around =<= =>=.

- =mi= + =!=, =@=, =#=, =$=, =%=, =^=, =&=, =*=, =~=, ~=~, =_= ::
  Mark the inner part of the region enclosed in this characters.

- =ma= + =!=, =@=, =#=, =$=, =%=, =^=, =&=, =*=, =~=, ~=~, =_= ::
  Mark the whole region enclosed in this characters.

** Surround

- =mm= :: Go to matching bracket.

- =ms= :: Surround selection.

  Left brackets — =(=, =[=, ={= — add extra spaces around the surrounded region.
  If the selection is linewise (make with =x=), the delimiters are placed on
  separate lines.
  
  Right brackets — =)=, =]=, =}= — do the opposite: they remove all spaces or
  newlines from the selection and are inserted tightly.

- =md= :: Delete surround.

- =mr= :: Change (replace) surround.

** Search

- =/=, =?= :: Search for regex pattern *forward* / *backward*.

- =*= ::
  Construct regexp from all current selections and store it in the ~/~ register.
  Auto-detect word boundaries at the beginning and end of the search
  patterns.

- =M-*= ::
  Construct regexp from all current selections and store it in the ~/~ register.

- =n= / =N= :: Select *next* / *previous* match to the regexp from the ~/~ register.

** Jumplist

- =C-s= :: Save current main cursor position to the mark-ring.

- =C-o= / =C-i= ::
  Go-to previous/next position in the mark-ring. Read help for
  ~hel-backward-mark-ring~ command.

- =C-O= / =C-I= ::
  Go-to previous/next position in the ~global-mark-ring~ (read about it in Emacs
  manual).

** Miscellaneous

- =zx= :: save buffer

- =.=  :: repeat last command
- =gc= :: comment selection

- =go= :: ~imenu~
- =ga= :: Show various information about the position before cursor: code point,
  faces, overlays, etc.

- =zn= :: Narrow buffer to selection.
- =zw= :: Remove narrowing.

- =gq= :: Fill each of the paragraphs in the region.
- =gQ= :: Fill the region as if it were a single paragraph.

- =gf= :: Open file path under cursor (like in Vim)
- =gx= :: Open URL under cursor (like in Vim)

- =[ SPC= / =] SPC= :: Add empty line above/below.

** Xref (Emacs go-to definition framework)

- =gd= :: Jump to definition.

- =C-w gd= :: Jump to definition in another window.

- =gr= :: Find all references.

- =[x= / =]x= ::
  Go to the *previous* / *next* position in xref history. It appeares to be very handy
  to have these positions in a stack separate from the jumplist.

* Insert state

In Insert state Hel doesn’t bind any keys by default, so you get the standard
Emacs editing experience here.

